name: flutter_hooks_gallery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^6.0.0
  flutter:
    sdk: flutter
  flutter_hooks:
    path: ../
  provider: 3.1.0+1
  shared_preferences: ^0.4.3

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
