language: bash
os:
  - osx
sudo: false
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=$PATH:$PWD/flutter/bin
  - export PATH=$PATH:$PWD/flutter/bin/cache/dart-sdk/bin
  - flutter doctor
  - cd -
script:
  # abort on error
  - set -e
  - flutter packages get
  - flutter format --set-exit-if-changed lib example
  - flutter analyze lib example
  - flutter test --no-pub --coverage
  # export coverage
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
