name: flutter_hooks
description: A flutter implementation of React hooks. It adds a new kind of widget with enhanced code reuse.
homepage: https://github.com/rrousselGit/flutter_hooks
author: Remi Rousselet <darky12s@gmail.com>

version: 0.4.0

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">= 1.5.0-pre <= 2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  mockito: ">=4.0.0 <5.0.0"
